version: "3.5"

services:
  backend:
    container_name: backend 
    image: python
    restart: always
    ports:
      - 127.0.0.1:22253:5000/tcp
    volumes:
      - .:/code
    command: ["bash", "-c", "cd code && pip install flask gunicorn eventlet && pip install -r requirements.txt && gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5000 main:app"]
    network_mode: "bridge"